# generated by datamodel-codegen:
#   filename:  http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.yml
#   timestamp: 2022-01-07T16:18:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Translation(BaseModel):
    updated_at: str
    locale: str
    content: str


class Message(BaseModel):
    id: str
    author: str
    heading: str
    content: str
    severity: str
    created_at: str
    updated_at: str
    translations: List[Translation]


class Incident(BaseModel):
    id: int
    active: bool
    created_at: str
    updates: List[Message]


class Service(BaseModel):
    name: str
    slug: str
    status: str
    incidents: List[Incident]


class ShardStatus(BaseModel):
    locales: List[str]
    hostname: str
    name: str
    services: List[Service]
    slug: str
    region_tag: str
