# generated by datamodel-codegen:
#   filename:  http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.yml
#   timestamp: 2022-01-07T16:18:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class PlayerDto(BaseModel):
    name: str
    rank: int
    lp: int = Field(..., description="League points.")


class LeaderboardDto(BaseModel):
    players: List[PlayerDto] = Field(..., description="A list of players in Master tier.")
