# generated by datamodel-codegen:
#   filename:  http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.yml
#   timestamp: 2022-01-07T16:18:58+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Union

from pydantic import BaseModel, Field


class MaintenanceStatus(Enum):
    scheduled = "scheduled"
    in_progress = "in_progress"
    complete = "complete"


class IncidentSeverity(Enum):
    info = "info"
    warning = "warning"
    critical = "critical"


class Platforms(Enum):
    windows = "windows"
    macos = "macos"
    android = "android"
    ios = "ios"
    ps4 = "ps4"
    xbone = "xbone"
    switch = "switch"


class ContentDto(BaseModel):
    locale: str
    content: str


class PublishLocations(Enum):
    riotclient = "riotclient"
    riotstatus = "riotstatus"
    game = "game"


class UpdateDto(BaseModel):
    id: int
    author: str
    publish: bool
    publish_locations: Union[List[str], PublishLocations] = Field(
        ..., description="(Legal values: riotclient, riotstatus, game)"
    )
    translations: List[ContentDto]
    created_at: str
    updated_at: str


class StatusDto(BaseModel):
    id: int
    maintenance_status: MaintenanceStatus = Field(
        ..., description="(Legal values:  scheduled,  in_progress,  complete)"
    )
    incident_severity: IncidentSeverity = Field(..., description="(Legal values:  info,  warning,  critical)")
    titles: List[ContentDto]
    updates: List[UpdateDto]
    created_at: str
    archive_at: str
    updated_at: str
    platforms: Union[List[str], Platforms] = Field(
        ...,
        description="(Legal values: windows, macos, android, ios, ps4, xbone, switch)",
    )


class PlatformDataDto(BaseModel):
    id: str
    name: str
    locales: List[str]
    maintenances: List[StatusDto]
    incidents: List[StatusDto]
