# generated by datamodel-codegen:
#   filename:  http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.yml
#   timestamp: 2022-01-07T16:18:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PlayerDto(BaseModel):
    puuid: Optional[str] = Field(None, description="This field may be omitted if the player has been anonymized.")
    gameName: Optional[str] = Field(None, description="This field may be omitted if the player has been anonymized.")
    tagLine: Optional[str] = Field(None, description="This field may be omitted if the player has been anonymized.")
    leaderboardRank: int
    rankedRating: int
    numberOfWins: int


class LeaderboardDto(BaseModel):
    shard: str = Field(..., description="The shard for the given leaderboard.")
    actId: str = Field(
        ...,
        description="The act id for the given leaderboard. Act ids can be found using the val-content API.",
    )
    totalPlayers: int = Field(..., description="The total number of players in the leaderboard.")
    players: List[PlayerDto]
