# generated by datamodel-codegen:
#   filename:  http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.yml
#   timestamp: 2022-01-07T16:18:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LocalizedNamesDto(BaseModel):
    ar_AE: str = Field(..., alias="ar-AE")
    de_DE: str = Field(..., alias="de-DE")
    en_GB: str = Field(..., alias="en-GB")
    en_US: str = Field(..., alias="en-US")
    es_ES: str = Field(..., alias="es-ES")
    es_MX: str = Field(..., alias="es-MX")
    fr_FR: str = Field(..., alias="fr-FR")
    id_ID: str = Field(..., alias="id-ID")
    it_IT: str = Field(..., alias="it-IT")
    ja_JP: str = Field(..., alias="ja-JP")
    ko_KR: str = Field(..., alias="ko-KR")
    pl_PL: str = Field(..., alias="pl-PL")
    pt_BR: str = Field(..., alias="pt-BR")
    ru_RU: str = Field(..., alias="ru-RU")
    th_TH: str = Field(..., alias="th-TH")
    tr_TR: str = Field(..., alias="tr-TR")
    vi_VN: str = Field(..., alias="vi-VN")
    zh_CN: str = Field(..., alias="zh-CN")
    zh_TW: str = Field(..., alias="zh-TW")


class ActDto(BaseModel):
    name: str
    localizedNames: Optional[LocalizedNamesDto] = Field(
        None,
        description="This field is excluded from the response when a locale is set",
    )
    id: str
    isActive: bool


class ContentItemDto(BaseModel):
    name: str
    localizedNames: Optional[LocalizedNamesDto] = Field(
        None,
        description="This field is excluded from the response when a locale is set",
    )
    id: str
    assetName: str
    assetPath: Optional[str] = Field(
        None,
        description="This field is only included for maps and game modes. These values are used in the match response.",
    )


class ContentDto(BaseModel):
    version: str
    characters: List[ContentItemDto]
    maps: List[ContentItemDto]
    chromas: List[ContentItemDto]
    skins: List[ContentItemDto]
    skinLevels: List[ContentItemDto]
    equips: List[ContentItemDto]
    gameModes: List[ContentItemDto]
    sprays: List[ContentItemDto]
    sprayLevels: List[ContentItemDto]
    charms: List[ContentItemDto]
    charmLevels: List[ContentItemDto]
    playerCards: List[ContentItemDto]
    playerTitles: List[ContentItemDto]
    acts: List[ActDto]
